# Generated by Django 5.1.7 on 2025-03-18 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_profile_is_active_profile_is_verified"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="profile",
            table="profiles",
        ),
    ]
