# Generated by Django 5.1.7 on 2025-04-04 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0005_remove_profile_email_remove_profile_is_verified_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="is_complete",
            field=models.BooleanField(default=False),
        ),
    ]
