# Generated by Django 5.1.7 on 2025-03-18 14:37

import core.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("profiles", "0004_profile_photo"),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=core.utils.generate_id,
                        editable=False,
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("account_number", models.CharField(max_length=100, unique=True)),
                ("identity_number", models.CharField(max_length=100)),
                ("tax_number", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "current_balance",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("currency", models.CharField(default="IDR", max_length=10)),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("gold", "Gold"),
                            ("silver", "Silver"),
                            ("starter", "Starter"),
                        ],
                        max_length=10,
                    ),
                ),
                ("is_have_limit", models.BooleanField(default=False)),
                (
                    "limit",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("suspended", "Suspended"),
                            ("closed", "Closed"),
                            ("pending", "Pending"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profiles.profile",
                    ),
                ),
            ],
            options={
                "db_table": "accounts",
                "indexes": [
                    models.Index(
                        fields=["account_number", "profile"],
                        name="accounts_account_20ec5f_idx",
                    )
                ],
            },
        ),
    ]
