# Generated by Django 5.1.7 on 2025-04-04 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="card_holder_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="account",
            name="card_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
