# Generated by Django 5.1.7 on 2025-04-04 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_account_card_holder_name_account_card_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="account_type",
            field=models.CharField(
                choices=[
                    ("gold", "Gold"),
                    ("silver", "Silver"),
                    ("starter", "Starter"),
                ],
                default="starter",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="current_balance",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="account",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("suspended", "Suspended"),
                    ("closed", "Closed"),
                    ("pending", "Pending"),
                ],
                default="active",
                max_length=10,
            ),
        ),
    ]
