# Generated by Django 5.1.7 on 2025-04-05 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_account_account_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="account_purpose",
            field=models.CharField(blank=True, null=True),
        ),
    ]
