# Generated by Django 5.1.7 on 2025-04-06 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0003_alter_transaction_success_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="success_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
